// Banco de casos clínicos para o modo Diagnóstico (estilo Doctordle).
// Cada caso tem pistas progressivas: a pista 0 aparece primeiro; a cada
// tentativa errada, a próxima pista é revelada. O jogador tem 6 tentativas.

export interface ClinicalCase {
  id: string;
  diagnosis: string;          // resposta correta (nome canônico)
  aliases: string[];          // formas aceitas alternativas
  specialty: string;          // especialidade / área
  clues: string[];            // pistas progressivas (clues[0] = primeira)
  explanation: string;        // explicação exibida ao final
}

export const CLINICAL_CASES: ClinicalCase[] = [
  {
    id: 'case_001',
    diagnosis: 'Osteossarcoma',
    aliases: ['osteosarcoma', 'sarcoma osteogênico', 'sarcoma osteogenico'],
    specialty: 'Ortopedia / Oncologia',
    clues: [
      'Menino de 14 anos apresenta dor progressiva na perna esquerda há 2 meses, pior à noite.',
      'Ao exame, há massa dolorosa e edema na região do joelho, próxima à metáfise distal do fêmur.',
      'A dor não melhora com repouso e houve perda de peso não intencional recente.',
      'Radiografia mostra lesão lítica e esclerótica com reação periosteal em "raios de sol" (sunburst) e triângulo de Codman.',
      'Fosfatase alcalina e LDH séricas elevadas.',
      'Biópsia revela células fusiformes malignas produzindo matriz osteoide.',
    ],
    explanation: 'Osteossarcoma é o tumor ósseo maligno primário mais comum em adolescentes, com pico na segunda década. Acomete tipicamente a metáfise de ossos longos (fêmur distal, tíbia proximal, úmero proximal). Radiografia clássica: reação periosteal em "sunburst" e triângulo de Codman. Tratamento: quimioterapia neoadjuvante + ressecção cirúrgica.',
  },
  {
    id: 'case_002',
    diagnosis: 'Apendicite aguda',
    aliases: ['apendicite', 'apendicite aguda'],
    specialty: 'Cirurgia Geral',
    clues: [
      'Homem de 22 anos com dor abdominal há 18 horas, inicialmente periumbilical.',
      'A dor migrou e se localizou na fossa ilíaca direita, acompanhada de náuseas e anorexia.',
      'Febre baixa (37,9°C) e leucocitose com desvio à esquerda.',
      'Sinal de Blumberg positivo no ponto de McBurney; dor à descompressão.',
      'Sinal de Rovsing positivo (dor em FID à palpação da FIE).',
      'USG/TC mostra apêndice espessado (>6 mm), não compressível, com borramento da gordura periapendicular.',
    ],
    explanation: 'Apendicite aguda é a emergência cirúrgica abdominal mais comum. Clássico: dor periumbilical que migra para FID (ponto de McBurney), anorexia, náusea. Sinais: Blumberg, Rovsing, psoas, obturador. Tratamento: apendicectomia (aberta ou laparoscópica).',
  },
  {
    id: 'case_003',
    diagnosis: 'Infarto agudo do miocárdio',
    aliases: ['iam', 'infarto do miocárdio', 'infarto do miocardio', 'infarto agudo do miocardio', 'iamcsst', 'síndrome coronariana aguda'],
    specialty: 'Cardiologia',
    clues: [
      'Homem de 58 anos, tabagista e hipertenso, com dor torácica opressiva há 40 minutos.',
      'A dor irradia para o braço esquerdo e mandíbula, associada a sudorese fria e náuseas.',
      'A dor não alivia com repouso nem com nitrato sublingual.',
      'ECG mostra supradesnivelamento do segmento ST em parede inferior (DII, DIII, aVF).',
      'Troponina I sérica marcadamente elevada.',
      'Cateterismo revela oclusão total da artéria coronária direita.',
    ],
    explanation: 'IAM com supra de ST: oclusão coronária total causando necrose transmural. Dor anginosa típica >20 min, irradiação, sintomas neurovegetativos. ECG com supra de ST + troponina elevada. Reperfusão imediata: angioplastia primária <90 min ou trombólise se indisponível.',
  },
  {
    id: 'case_004',
    diagnosis: 'Meningite bacteriana',
    aliases: ['meningite', 'meningite bacteriana', 'meningite meningocócica', 'meningite meningococica'],
    specialty: 'Infectologia / Neurologia',
    clues: [
      'Jovem de 19 anos, universitário, com febre alta, cefaleia intensa e vômitos há 12 horas.',
      'Apresenta rigidez de nuca e fotofobia importante.',
      'Sinais de Kernig e Brudzinski positivos.',
      'Surgem petéquias e lesões purpúricas em tronco e membros.',
      'Punção lombar: líquor turvo, com pleocitose neutrofílica, glicose baixa e proteína elevada.',
      'Bacterioscopia do líquor revela diplococos gram-negativos.',
    ],
    explanation: 'Meningite bacteriana por Neisseria meningitidis (meningococo): emergência médica. Tríade clássica: febre, rigidez de nuca, alteração do estado mental. Petéquias/púrpura sugerem meningococcemia. Líquor: neutrofílico, glicose ↓, proteína ↑. Tratamento imediato: ceftriaxona + dexametasona. Notificação compulsória.',
  },
  {
    id: 'case_005',
    diagnosis: 'Diabetes mellitus tipo 1',
    aliases: ['dm1', 'diabetes tipo 1', 'diabetes mellitus tipo 1', 'diabetes'],
    specialty: 'Endocrinologia / Pediatria',
    clues: [
      'Criança de 9 anos com poliúria, polidipsia e polifagia há 3 semanas.',
      'Perda de peso significativa apesar do aumento do apetite.',
      'Nos últimos dias: náuseas, dor abdominal e respiração rápida e profunda.',
      'Hálito cetônico (odor de maçã podre) e desidratação.',
      'Glicemia capilar de 480 mg/dL e cetonúria intensa.',
      'Gasometria: acidose metabólica com ânion gap elevado e bicarbonato baixo.',
    ],
    explanation: 'DM tipo 1 abrindo o quadro com cetoacidose diabética (CAD). Destruição autoimune das células beta → deficiência absoluta de insulina. Poliúria, polidipsia, polifagia, perda de peso. CAD: hiperglicemia + cetose + acidose. Tratamento: hidratação, insulina IV, reposição de potássio.',
  },
  {
    id: 'case_006',
    diagnosis: 'Pneumonia adquirida na comunidade',
    aliases: ['pneumonia', 'pac', 'pneumonia comunitária', 'pneumonia comunitaria', 'pneumonia adquirida na comunidade'],
    specialty: 'Pneumologia',
    clues: [
      'Homem de 65 anos com febre, tosse produtiva e dor torácica pleurítica há 4 dias.',
      'Expectoração amarelo-esverdeada e dispneia progressiva.',
      'Ao exame: taquipneia, estertores crepitantes e macicez à percussão na base direita.',
      'Aumento do frêmito toracovocal e broncofonia na base direita.',
      'Radiografia de tórax mostra consolidação com broncograma aéreo em lobo inferior direito.',
      'Leucocitose com desvio à esquerda; agente mais provável: Streptococcus pneumoniae.',
    ],
    explanation: 'Pneumonia adquirida na comunidade, agente mais comum: Streptococcus pneumoniae. Febre, tosse produtiva, dor pleurítica, dispneia. Exame: crepitações, síndrome de consolidação. Rx: consolidação com broncograma aéreo. Avaliar gravidade (CURB-65) para definir local de tratamento.',
  },
  {
    id: 'case_007',
    diagnosis: 'Acidente vascular cerebral isquêmico',
    aliases: ['avc', 'avc isquêmico', 'avc isquemico', 'acidente vascular cerebral', 'derrame', 'isquemia cerebral'],
    specialty: 'Neurologia',
    clues: [
      'Mulher de 72 anos, hipertensa e com fibrilação atrial, com início súbito de fraqueza.',
      'Hemiparesia à direita e desvio da comissura labial iniciados há 1 hora.',
      'Afasia de expressão (dificuldade para falar) associada.',
      'Não há cefaleia intensa nem rebaixamento importante do nível de consciência.',
      'TC de crânio sem contraste não mostra sangramento (exclui hemorragia).',
      'Território acometido: artéria cerebral média esquerda; origem provavelmente cardioembólica.',
    ],
    explanation: 'AVC isquêmico: déficit neurológico focal súbito. FA é fonte cardioembólica comum. Território de ACM: hemiparesia/hemiplegia contralateral, afasia (hemisfério dominante). TC exclui hemorragia. Trombólise com alteplase até 4,5h se sem contraindicações; trombectomia em oclusão de grande vaso.',
  },
  {
    id: 'case_008',
    diagnosis: 'Lúpus eritematoso sistêmico',
    aliases: ['les', 'lúpus', 'lupus', 'lúpus eritematoso sistêmico', 'lupus eritematoso sistemico'],
    specialty: 'Reumatologia',
    clues: [
      'Mulher de 26 anos com fadiga, artralgia e febre baixa há 2 meses.',
      'Eritema em asa de borboleta (malar) que poupa os sulcos nasolabiais.',
      'Fotossensibilidade e úlceras orais indolores.',
      'Poliartrite simétrica de pequenas articulações, sem erosões.',
      'Exames: proteinúria, ANA positivo em títulos altos e anti-DNA de dupla hélice positivo.',
      'Complemento (C3 e C4) consumido; anti-Sm positivo (específico).',
    ],
    explanation: 'Lúpus eritematoso sistêmico: doença autoimune multissistêmica, mulheres jovens. Rash malar, fotossensibilidade, úlceras orais, artrite, nefrite. ANA sensível; anti-dsDNA e anti-Sm específicos; complemento baixo na atividade. Tratamento: hidroxicloroquina, corticoide, imunossupressores conforme gravidade.',
  },
  {
    id: 'case_009',
    diagnosis: 'Tuberculose pulmonar',
    aliases: ['tuberculose', 'tb', 'tuberculose pulmonar', 'tbc'],
    specialty: 'Infectologia / Pneumologia',
    clues: [
      'Homem de 40 anos, morador de rua, com tosse há mais de 3 semanas.',
      'Febre vespertina, sudorese noturna e perda de peso importante.',
      'A tosse tornou-se produtiva, com episódios de escarro hemoptoico.',
      'Radiografia mostra infiltrado com cavitação em ápice pulmonar direito.',
      'Baciloscopia de escarro (BAAR) positiva.',
      'TRM-TB (teste rápido molecular) confirma Mycobacterium tuberculosis sensível à rifampicina.',
    ],
    explanation: 'Tuberculose pulmonar: tosse >3 semanas, febre vespertina, sudorese noturna, emagrecimento. Rx: cavitação apical. Diagnóstico: baciloscopia, TRM-TB, cultura. Tratamento: esquema RIPE (rifampicina, isoniazida, pirazinamida, etambutol) por 6 meses. Notificação compulsória.',
  },
  {
    id: 'case_010',
    diagnosis: 'Colecistite aguda',
    aliases: ['colecistite', 'colecistite aguda', 'colecistite calculosa'],
    specialty: 'Cirurgia Geral',
    clues: [
      'Mulher de 45 anos, obesa, com dor no hipocôndrio direito há 1 dia.',
      'A dor começou após refeição gordurosa e irradia para a escápula direita.',
      'Náuseas, vômitos e febre baixa associados.',
      'Sinal de Murphy positivo (parada da inspiração à palpação do HD).',
      'USG mostra cálculos na vesícula, parede espessada (>4 mm) e líquido perivesicular.',
      'Leucocitose; a vesícula está distendida e dolorosa.',
    ],
    explanation: 'Colecistite aguda: inflamação da vesícula, geralmente por obstrução do ducto cístico por cálculo. Fatores de risco: "4 Fs" (female, forty, fat, fertile). Dor em HD pós-prandial, sinal de Murphy. USG: cálculos, parede espessada. Tratamento: colecistectomia (idealmente precoce) + antibiótico.',
  },
  {
    id: 'case_011',
    diagnosis: 'Embolia pulmonar',
    aliases: ['tep', 'embolia pulmonar', 'tromboembolismo pulmonar', 'tromboembolia pulmonar'],
    specialty: 'Pneumologia / Cardiologia',
    clues: [
      'Mulher de 55 anos, pós-operatório de cirurgia ortopédica, com dispneia súbita.',
      'Dor torácica pleurítica e taquicardia (FC 120 bpm).',
      'Um dos membros inferiores está edemaciado, doloroso e mais quente.',
      'Hipoxemia e taquipneia; D-dímero muito elevado.',
      'ECG com padrão S1Q3T3 e taquicardia sinusal.',
      'Angio-TC de tórax mostra falha de enchimento em artérias pulmonares.',
    ],
    explanation: 'Tromboembolismo pulmonar: geralmente por TVP de membros inferiores. Fatores de risco: imobilização, pós-operatório, câncer, trombofilia (tríade de Virchow). Dispneia súbita, dor pleurítica, taquicardia. Angio-TC é o exame de escolha. Tratamento: anticoagulação; trombólise se instabilidade.',
  },
  {
    id: 'case_012',
    diagnosis: 'Doença de Crohn',
    aliases: ['crohn', 'doença de crohn', 'doenca de crohn'],
    specialty: 'Gastroenterologia',
    clues: [
      'Homem de 24 anos com dor abdominal crônica e diarreia há 6 meses.',
      'Perda de peso, fadiga e episódios de febre baixa.',
      'Diarreia por vezes com sangue; dor mais intensa em fossa ilíaca direita.',
      'Apresenta aftas orais, artralgia e uma fístula perianal.',
      'Colonoscopia mostra lesões salteadas (skip lesions) com aspecto em "pedra de calçamento".',
      'Biópsia revela inflamação transmural com granulomas não caseosos.',
    ],
    explanation: 'Doença de Crohn: doença inflamatória intestinal que pode acometer todo o TGI (boca ao ânus), com predileção pelo íleo terminal. Inflamação transmural, lesões salteadas, granulomas, fístulas. Manifestações extraintestinais: aftas, artrite, uveíte. Diferencia-se da retocolite ulcerativa (acometimento contínuo, mucoso).',
  },
  {
    id: 'case_013',
    diagnosis: 'Hipotireoidismo',
    aliases: ['hipotireoidismo', 'hashimoto', 'tireoidite de hashimoto'],
    specialty: 'Endocrinologia',
    clues: [
      'Mulher de 50 anos com fadiga, ganho de peso e intolerância ao frio há meses.',
      'Pele seca, queda de cabelo e constipação.',
      'Bradicardia, lentificação de reflexos e edema periorbital.',
      'Bócio de consistência firme à palpação da tireoide.',
      'Laboratório: TSH elevado e T4 livre reduzido.',
      'Anticorpos anti-TPO positivos em títulos elevados.',
    ],
    explanation: 'Hipotireoidismo primário, causa mais comum: tireoidite de Hashimoto (autoimune, anti-TPO+). Fadiga, ganho de peso, intolerância ao frio, pele seca, constipação, bradicardia. Laboratório: TSH ↑, T4 livre ↓. Tratamento: levotiroxina oral em jejum, com ajuste guiado pelo TSH.',
  },
  {
    id: 'case_014',
    diagnosis: 'Pancreatite aguda',
    aliases: ['pancreatite', 'pancreatite aguda'],
    specialty: 'Gastroenterologia / Cirurgia',
    clues: [
      'Homem de 48 anos, etilista, com dor abdominal epigástrica intensa há 12 horas.',
      'A dor irradia para o dorso (em faixa) e melhora ao inclinar-se para frente.',
      'Vômitos persistentes e distensão abdominal.',
      'Amilase e lipase séricas elevadas mais de 3 vezes o limite superior.',
      'Equimose periumbilical (sinal de Cullen) e em flancos (sinal de Grey-Turner).',
      'TC mostra edema e inflamação do pâncreas com coleções peripancreáticas.',
    ],
    explanation: 'Pancreatite aguda: causas mais comuns são litíase biliar e álcool. Dor epigástrica intensa em faixa, irradiando ao dorso. Diagnóstico: 2 de 3 critérios (dor típica, lipase/amilase >3x, imagem). Sinais de Cullen e Grey-Turner indicam gravidade (hemorrágica). Tratamento: suporte, hidratação, analgesia, jejum.',
  },
  {
    id: 'case_015',
    diagnosis: 'Asma',
    aliases: ['asma', 'crise asmática', 'crise asmatica', 'asma brônquica'],
    specialty: 'Pneumologia',
    clues: [
      'Jovem de 16 anos com episódios recorrentes de dispneia e tosse seca noturna.',
      'Os sintomas pioram com exercício, poeira e mudanças de temperatura.',
      'Durante as crises há sibilância expiratória audível e sensação de aperto no peito.',
      'Melhora rápida dos sintomas após uso de broncodilatador (salbutamol).',
      'Espirometria mostra padrão obstrutivo com resposta ao broncodilatador (VEF1 ↑ >12%).',
      'História pessoal e familiar de atopia (rinite alérgica, eczema).',
    ],
    explanation: 'Asma: doença inflamatória crônica das vias aéreas com obstrução reversível. Dispneia, sibilância, tosse, aperto torácico, piora noturna e com gatilhos. Espirometria: obstrução reversível com broncodilatador. Tratamento: corticoide inalatório (controlador) + broncodilatador (alívio).',
  },
  {
    id: 'case_016',
    diagnosis: 'Anemia ferropriva',
    aliases: ['anemia ferropriva', 'anemia por deficiência de ferro', 'anemia ferropênica', 'anemia ferropenica'],
    specialty: 'Hematologia',
    clues: [
      'Mulher de 35 anos com fadiga, palidez e queda de cabelo há meses.',
      'Refere fluxo menstrual abundante e prolongado.',
      'Apresenta unhas quebradiças (coiloníquia) e desejo de comer gelo (pagofagia).',
      'Hemograma: anemia microcítica e hipocrômica.',
      'Ferritina sérica baixa e capacidade de ligação do ferro (TIBC) elevada.',
      'RDW aumentado; ferro sérico baixo.',
    ],
    explanation: 'Anemia ferropriva: causa mais comum de anemia no mundo. Em mulheres em idade fértil, a menorragia é causa frequente. Fadiga, palidez, coiloníquia, pagofagia. Hemograma: microcítica hipocrômica. Ferritina baixa (mais específica). Tratamento: sulfato ferroso oral + investigar/tratar a causa do sangramento.',
  },
  {
    id: 'case_017',
    diagnosis: 'Dengue',
    aliases: ['dengue', 'dengue clássica', 'dengue classica'],
    specialty: 'Infectologia',
    clues: [
      'Homem de 30 anos com febre alta de início súbito há 3 dias.',
      'Cefaleia intensa, dor retro-orbitária e mialgia importante ("febre quebra-ossos").',
      'Exantema maculopapular e prurido no tronco.',
      'Mora em região endêmica com surto sazonal recente após chuvas.',
      'Hemograma: leucopenia e plaquetopenia.',
      'Prova do laço positiva; sorologia/NS1 reagente para o vírus.',
    ],
    explanation: 'Dengue: arbovirose transmitida pelo Aedes aegypti. Febre alta súbita, cefaleia, dor retro-orbitária, mialgia, artralgia, exantema. Leucopenia e plaquetopenia. Sinais de alarme (dor abdominal, vômitos, sangramento) indicam gravidade. Manejo: hidratação; evitar AINEs/AAS. Notificação compulsória.',
  },
  {
    id: 'case_018',
    diagnosis: 'Insuficiência cardíaca',
    aliases: ['insuficiência cardíaca', 'insuficiencia cardiaca', 'ic', 'icc', 'insuficiência cardíaca congestiva'],
    specialty: 'Cardiologia',
    clues: [
      'Homem de 68 anos, hipertenso e com IAM prévio, com dispneia progressiva aos esforços.',
      'Ortopneia (dorme com várias travesseiros) e dispneia paroxística noturna.',
      'Edema de membros inferiores bilateral e ganho de peso recente.',
      'Ao exame: estertores crepitantes bibasais, turgência jugular e hepatomegalia.',
      'Terceira bulha (B3) audível; ecocardiograma com fração de ejeção reduzida (35%).',
      'BNP/NT-proBNP elevado; radiografia com cardiomegalia e congestão pulmonar.',
    ],
    explanation: 'Insuficiência cardíaca com fração de ejeção reduzida. Dispneia aos esforços, ortopneia, DPN, edema, turgência jugular, B3. BNP elevado, eco com FE ↓. Tratamento que reduz mortalidade: IECA/BRA/ARNI + betabloqueador + antagonista de aldosterona + iSGLT2; diuréticos para congestão.',
  },
  {
    id: 'case_019',
    diagnosis: 'Cetoacidose diabética',
    aliases: ['cetoacidose diabética', 'cetoacidose diabetica', 'cad'],
    specialty: 'Endocrinologia / Emergência',
    clues: [
      'Adolescente de 15 anos, diabético tipo 1, que suspendeu a insulina há 2 dias.',
      'Dor abdominal, náuseas e vômitos com piora do estado geral.',
      'Respiração rápida e profunda (Kussmaul) e hálito cetônico.',
      'Desidratação, taquicardia e rebaixamento leve do sensório.',
      'Glicemia 520 mg/dL, cetonúria intensa e cetonemia.',
      'Gasometria: pH 7,1, bicarbonato baixo e ânion gap elevado.',
    ],
    explanation: 'Cetoacidose diabética: complicação aguda do DM (mais comum no tipo 1), frequentemente por omissão de insulina ou infecção. Hiperglicemia + cetose + acidose metabólica com ânion gap elevado. Respiração de Kussmaul, hálito cetônico. Tratamento: hidratação vigorosa, insulina IV, reposição de potássio.',
  },
  {
    id: 'case_020',
    diagnosis: 'Artrite reumatoide',
    aliases: ['artrite reumatoide', 'artrite reumatóide', 'ar'],
    specialty: 'Reumatologia',
    clues: [
      'Mulher de 45 anos com dor e edema em pequenas articulações das mãos há 4 meses.',
      'Rigidez matinal com duração superior a 1 hora.',
      'Acometimento simétrico de metacarpofalângicas e interfalângicas proximais (poupa as distais).',
      'Fadiga e nódulos subcutâneos em superfícies extensoras.',
      'Fator reumatoide e anti-CCP positivos; VHS e PCR elevados.',
      'Radiografia mostra erosões articulares e redução do espaço articular.',
    ],
    explanation: 'Artrite reumatoide: poliartrite inflamatória crônica simétrica de pequenas articulações, com rigidez matinal >1h. Poupa interfalângicas distais. Anti-CCP é o marcador mais específico. Erosões ósseas na radiografia. Tratamento: metotrexato (1ª linha) ± biológicos; meta de remissão (treat-to-target).',
  },
  {
    id: 'case_021',
    diagnosis: 'Cólica renal',
    aliases: ['cólica renal', 'colica renal', 'nefrolitíase', 'nefrolitiase', 'litíase renal', 'litiase renal', 'urolitíase', 'urolitiase', 'cálculo renal', 'calculo renal'],
    specialty: 'Urologia / Nefrologia',
    clues: [
      'Homem de 40 anos com dor lombar súbita e intensa há 3 horas.',
      'A dor irradia para a região inguinal e testículo do mesmo lado.',
      'O paciente está agitado, sem posição antálgica, com náuseas e vômitos.',
      'Hematúria macroscópica; sem febre.',
      'Exame de urina com hematúria microscópica; punho-percussão lombar positiva.',
      'TC de abdome sem contraste mostra cálculo em ureter proximal com dilatação a montante.',
    ],
    explanation: 'Cólica renal por nefrolitíase: dor lombar súbita e intensa em cólica, irradiando para região inguinal/genital, com paciente inquieto (sem posição de alívio). Hematúria comum. TC sem contraste é o padrão-ouro. Tratamento: analgesia (AINEs), hidratação; cálculos <5 mm costumam ser eliminados espontaneamente.',
  },
  {
    id: 'case_022',
    diagnosis: 'Hemorragia subaracnoidea',
    aliases: ['hemorragia subaracnoidea', 'hsa', 'hemorragia subaracnóidea', 'aneurisma roto'],
    specialty: 'Neurologia / Neurocirurgia',
    clues: [
      'Mulher de 50 anos com cefaleia de início súbito e intensidade máxima ("a pior da vida").',
      'A cefaleia atingiu o pico em segundos ("thunderclap") durante esforço físico.',
      'Náuseas, vômitos e rigidez de nuca.',
      'Breve perda de consciência no início do quadro; fotofobia.',
      'TC de crânio mostra sangue nas cisternas da base e sulcos (espaço subaracnoideo).',
      'Angiografia revela aneurisma sacular roto na artéria comunicante anterior.',
    ],
    explanation: 'Hemorragia subaracnoidea: cefaleia "thunderclap" (a pior da vida, pico em segundos), classicamente por ruptura de aneurisma sacular. Sinais meníngeos, rebaixamento, fotofobia. TC sem contraste (sangue nas cisternas); se negativa e alta suspeita, punção lombar. Tratamento: clipagem/embolização do aneurisma.',
  },
  {
    id: 'case_023',
    diagnosis: 'Doença de Parkinson',
    aliases: ['doença de parkinson', 'doenca de parkinson', 'parkinson', 'parkinsonismo'],
    specialty: 'Neurologia',
    clues: [
      'Homem de 68 anos com tremor na mão direita, notado em repouso.',
      'O tremor melhora com o movimento e piora com estresse ("contar moedas").',
      'Lentidão dos movimentos (bradicinesia) e dificuldade para iniciar a marcha.',
      'Rigidez em "roda denteada" e redução do balanço dos braços ao caminhar.',
      'Marcha em pequenos passos (festinante) e face inexpressiva (hipomimia).',
      'Melhora significativa dos sintomas com levodopa.',
    ],
    explanation: 'Doença de Parkinson: degeneração dos neurônios dopaminérgicos da substância negra. Tétrade: tremor de repouso, bradicinesia, rigidez (roda denteada) e instabilidade postural. Início assimétrico. Resposta à levodopa apoia o diagnóstico. Tratamento: levodopa, agonistas dopaminérgicos.',
  },
  {
    id: 'case_024',
    diagnosis: 'Úlcera péptica',
    aliases: ['úlcera péptica', 'ulcera peptica', 'úlcera gástrica', 'ulcera gastrica', 'úlcera duodenal', 'ulcera duodenal', 'doença ulcerosa péptica'],
    specialty: 'Gastroenterologia',
    clues: [
      'Homem de 42 anos com dor epigástrica em queimação há semanas.',
      'A dor melhora com alimentação e piora algumas horas após as refeições (padrão duodenal).',
      'Uso frequente de anti-inflamatórios (AINEs) para dor articular.',
      'Episódios de melena e leve anemia.',
      'Teste para Helicobacter pylori positivo.',
      'Endoscopia digestiva alta revela úlcera em bulbo duodenal.',
    ],
    explanation: 'Doença ulcerosa péptica: causas principais são H. pylori e uso de AINEs. Dor epigástrica em queimação; úlcera duodenal melhora com alimentação. Complicações: hemorragia (melena), perfuração. Diagnóstico: EDA. Tratamento: inibidor de bomba de prótons + erradicação do H. pylori.',
  },
  {
    id: 'case_025',
    diagnosis: 'Bronquiolite',
    aliases: ['bronquiolite', 'bronquiolite viral aguda', 'bronquiolite por vsr'],
    specialty: 'Pediatria',
    clues: [
      'Lactente de 5 meses com coriza e tosse há 3 dias, evoluindo com dificuldade respiratória.',
      'Sibilância difusa e taquipneia; recusa alimentar.',
      'Tiragem intercostal e batimento de asas nasais.',
      'Ocorrência no período de outono/inverno; contato com irmão resfriado.',
      'Ausculta com sibilos e estertores finos difusos; hipoxemia leve.',
      'Painel viral positivo para vírus sincicial respiratório (VSR).',
    ],
    explanation: 'Bronquiolite viral aguda: infecção de vias aéreas inferiores em lactentes <2 anos, agente mais comum VSR. Pródromo de IVAS seguido de sibilância, taquipneia, esforço respiratório. Sazonal (outono/inverno). Tratamento é de suporte: oxigênio, hidratação; não se usa rotineiramente broncodilatador/corticoide.',
  },
  {
    id: 'case_026',
    diagnosis: 'Sepse',
    aliases: ['sepse', 'choque séptico', 'choque septico', 'sepsis'],
    specialty: 'Medicina Intensiva / Emergência',
    clues: [
      'Idoso de 75 anos com febre, confusão mental e prostração há 1 dia.',
      'Foco infeccioso urinário provável (disúria e dor lombar prévias).',
      'Taquicardia, taquipneia e hipotensão (PA 85/50 mmHg).',
      'Extremidades mal perfundidas e oligúria.',
      'Lactato sérico elevado; leucocitose com desvio; qSOFA alterado.',
      'Hipotensão persistente exigindo vasopressor apesar de reposição volêmica.',
    ],
    explanation: 'Sepse: disfunção orgânica ameaçadora à vida por resposta desregulada à infecção. Choque séptico: hipotensão que requer vasopressor + lactato elevado apesar de volume. Manejo (bundle da 1ª hora): culturas, antibiótico precoce, cristaloide, medir lactato, vasopressor (noradrenalina) se necessário.',
  },
  {
    id: 'case_027',
    diagnosis: 'Apendagite / Diverticulite',
    aliases: ['diverticulite', 'diverticulite aguda'],
    specialty: 'Cirurgia Geral / Gastroenterologia',
    clues: [
      'Mulher de 60 anos com dor abdominal na fossa ilíaca esquerda há 2 dias.',
      'Alteração do hábito intestinal e febre baixa.',
      'Dor à palpação profunda em FIE, com defesa localizada.',
      'História de constipação crônica e dieta pobre em fibras.',
      'Leucocitose; PCR elevada.',
      'TC de abdome mostra divertículos no cólon sigmoide com espessamento e borramento da gordura pericólica.',
    ],
    explanation: 'Diverticulite aguda: inflamação de divertículos colônicos, mais comum no sigmoide. "Apendicite do lado esquerdo": dor em FIE, febre, alteração do hábito intestinal. TC confirma e estadia (classificação de Hinchey). Tratamento: casos não complicados com antibiótico/dieta; complicações (abscesso, perfuração) podem exigir cirurgia.',
  },
  {
    id: 'case_028',
    diagnosis: 'Hipertireoidismo',
    aliases: ['hipertireoidismo', 'doença de graves', 'doenca de graves', 'graves', 'tireotoxicose'],
    specialty: 'Endocrinologia',
    clues: [
      'Mulher de 32 anos com perda de peso apesar de apetite aumentado.',
      'Palpitações, tremor fino de extremidades e intolerância ao calor.',
      'Ansiedade, insônia e aumento do número de evacuações.',
      'Exoftalmia bilateral e bócio difuso com sopro à ausculta.',
      'TSH suprimido e T4 livre elevado.',
      'Anticorpo anti-receptor de TSH (TRAb) positivo.',
    ],
    explanation: 'Hipertireoidismo, causa mais comum: doença de Graves (autoimune, TRAb+). Perda de peso, palpitações, tremor, intolerância ao calor, hiperdefecação. Exoftalmia e bócio difuso são típicos de Graves. TSH ↓, T4 livre ↑. Tratamento: antitireoidianos (metimazol), iodo radioativo ou cirurgia; betabloqueador para sintomas.',
  },
  {
    id: 'case_029',
    diagnosis: 'Pré-eclâmpsia',
    aliases: ['pré-eclâmpsia', 'pre-eclampsia', 'pré eclampsia', 'pre eclampsia', 'eclâmpsia', 'eclampsia', 'dheg'],
    specialty: 'Ginecologia e Obstetrícia',
    clues: [
      'Gestante de 34 semanas, primigesta, com cefaleia e edema de mãos e face.',
      'Pressão arterial de 160/110 mmHg em duas medidas.',
      'Escotomas visuais e dor epigástrica em barra.',
      'Proteinúria significativa na urina de 24 horas.',
      'Reflexos exaltados; risco de progressão para convulsão.',
      'Laboratório com plaquetopenia e elevação de transaminases (sugerindo HELLP).',
    ],
    explanation: 'Pré-eclâmpsia: hipertensão (PA ≥140/90) após 20 semanas + proteinúria (ou lesão de órgão-alvo). Sinais de gravidade: PA ≥160/110, cefaleia, alterações visuais, dor epigástrica, plaquetopenia, HELLP. Tratamento: controle pressórico, sulfato de magnésio (prevenção de eclâmpsia) e resolução da gestação conforme indicação.',
  },
  {
    id: 'case_030',
    diagnosis: 'Herpes zoster',
    aliases: ['herpes zoster', 'herpes-zóster', 'zóster', 'zoster', 'cobreiro'],
    specialty: 'Dermatologia / Infectologia',
    clues: [
      'Homem de 65 anos com dor em queimação e formigamento em faixa no tronco há 3 dias.',
      'A dor é unilateral e não ultrapassa a linha média.',
      'Surgem vesículas agrupadas sobre base eritematosa seguindo um trajeto.',
      'A distribuição respeita um dermátomo torácico.',
      'História de varicela (catapora) na infância.',
      'Reativação do vírus varicela-zóster latente em gânglio sensitivo.',
    ],
    explanation: 'Herpes zóster: reativação do vírus varicela-zóster latente em gânglio da raiz dorsal. Dor/parestesia seguida de vesículas agrupadas com distribuição em dermátomo, unilateral, sem cruzar a linha média. Complicação: neuralgia pós-herpética. Tratamento: antiviral (aciclovir/valaciclovir) precoce + analgesia.',
  },
];
